import React from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createRootRoute, createRouter, Outlet, RouterProvider } from '@tanstack/react-router'
import '../../src/styles.css'
import catalog from './catalog-fixture.json'

// DEVELOPMENT FIXTURE ONLY: plan data is generated by Go; identity, scope,
// saved-secret metadata and request failures are artificial. No live API exists.
const params = new URLSearchParams(location.search)
const target = params.has('application') ? 'existing' : 'new'
const now = new Date().toISOString()
const application = { id:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', name:'fixture-outpost', display_name:'Existing review application', project:'fixture-review', environment:'development', revision:7, status:'unknown', spec:catalog.previous, observed:{observed_at:now, revision:7,status:'unknown',services:[]},created_at:now,updated_at:now }
const viewer=params.get('fixture')==='denied'
const identity={id:'fixture-user',name:'Development UI reviewer',email:'fixture@example.invalid',admin:false,owner:false,credential_type:'browser',permissions:['deployments:read',...(viewer?[]:['deployments:write'])],project_roles:[{project:'fixture-review',role:viewer?'viewer':'developer'}],host_permissions:[],avatar_url:''}
const fixture = {
  artificial:true,ready:false,target,application,catalog,requests:[] as unknown[],blocked:[] as string[],
  planMode:'success',secretMode:'success',deployMode:'error',holdPlan:false,holdDeploy:false,
  releasePlan:undefined as undefined|(()=>void),releaseDeploy:undefined as undefined|(()=>void),
  savedSecrets:[...new Set([...catalog.plans['new-baseline'].required_secrets,...catalog.plans['new-edited'].required_secrets])].filter(name=>name!=='custom-api-key'),
  plans:[] as any[],deployments:[] as any[],secretWrites:[] as unknown[],
  invalidate:()=>{},
  readMarkers:async()=> (await import('monaco-editor/esm/vs/editor/editor.api')).editor.getModelMarkers({}).map(marker=>({message:marker.message,line:marker.startLineNumber})),
  readEditor:async()=> (await import('monaco-editor/esm/vs/editor/editor.api')).editor.getModels().map(model=>model.getValue()),
}
Object.assign(window,{__templateFixture:fixture})
const fail=(message:string)=>({error:{code:'artificial_fixture',message:`Artificial fixture: ${message}`}})
window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{
  const request=input instanceof Request?input:new Request(new URL(String(input),location.origin),init)
  const url=new URL(request.url),method=init?.method||request.method
  let data:any,status=200,body:any
  if(url.origin===location.origin&&method==='GET'){
    if(url.pathname==='/api/me')data=identity
    else if(url.pathname==='/api/projects')data={items:[{id:'fixture-project',name:'fixture-review',display_name:'Artificial review project',personal:false,environments:[{name:'development'}]}]}
    else if(url.pathname==='/api/templates')data={items:catalog.items}
    else if(url.pathname===`/api/applications/${application.id}`)data=application
    else if(url.pathname==='/api/applications')data={items:[]}
    else if(url.pathname==='/api/secrets')data={items:fixture.savedSecrets.map(name=>({name,application:'fixture-outpost',updated_at:now}))}
    else if(url.pathname==='/api/license')data={valid:false,edition:'community',catalog:[]}
    else if(url.pathname==='/api/auth/status')data={deployment_mode:'self-hosted',setup_required:false,signup_enabled:false,password:true,providers:[],passkeys:true,totp:true,email_delivery:false}
    else if(url.pathname==='/api/alarms')data={items:[],summary:{active:0,unread:0},truncated:false}
    else if(url.pathname==='/api/teams')data={items:[]}
  }
  if(url.origin===location.origin&&method==='POST'&&url.pathname==='/api/templates/outpost/plan'){
    body=await request.json();fixture.plans.push(body)
    if(fixture.holdPlan)await new Promise<void>(resolve=>{fixture.releasePlan=resolve})
    if(fixture.planMode==='error'){status=400;data=fail('The edited TOML is invalid. Your edits are preserved.')}
    else{
      data=structuredClone(catalog.plans[`${target}-${body.toml?'edited':'baseline'}`])
      if(body.toml&&body.toml!==catalog.plans[`${target}-edited`].toml){status=400;data=fail('Only the exported edited fixture is accepted by this artificial server.')}
      else if(fixture.planMode==='stale')data.expected_revision++
    }
  }
  if(url.origin===location.origin&&((method==='POST'&&url.pathname.startsWith('/api/secrets/'))||(method==='PUT'&&url.pathname.startsWith('/api/templates/outpost/secrets/')))){
    body=await request.json();const name=url.pathname.split('/').at(-1)!
    fixture.secretWrites.push({method,name,valuePresent:typeof body.value==='string',scope:Object.fromEntries(url.searchParams)})
    if(fixture.secretMode==='error'){status=503;data=fail('The secret could not be saved. Your entry is preserved.')}
    else{fixture.savedSecrets.push(name);data={name,saved:true}}
    body={redacted:true}
  }
  if(url.origin===location.origin&&method==='POST'&&url.pathname==='/api/templates/outpost/deploy'){
    body=await request.json();fixture.deployments.push(body)
    if(fixture.holdDeploy)await new Promise<void>(resolve=>{fixture.releaseDeploy=resolve})
    status=503;data=fail('Deployment was not applied. The reviewed configuration is preserved.')
  }
  fixture.requests.push({method,path:url.pathname,status,...(body?{body}:{})})
  if(data===undefined){fixture.blocked.push(`${method} ${url.pathname}`);throw new Error(`Artificial fixture blocked ${method} ${url.pathname}`)}
  return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}})
}
const {DashboardShell}=await import('../../src/components/shell')
const query=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false,gcTime:0}}})
fixture.invalidate=()=>void query.invalidateQueries({queryKey:['application',application.id]})
const root=createRootRoute({component:()=> <DashboardShell><Outlet/></DashboardShell>})
const catalogRoute=(await import('../../src/routes/templates')).Route
const detailRoute=(await import('../../src/routes/templates.$templateId')).Route
catalogRoute.update({id:'/templates',path:'/templates',getParentRoute:()=>root} as never)
detailRoute.update({id:'/$templateId',path:'/$templateId',getParentRoute:()=>catalogRoute} as never)
const router=createRouter({routeTree:root.addChildren([catalogRoute.addChildren([detailRoute])]),defaultPreload:false})
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={query}><RouterProvider router={router}/></QueryClientProvider>)
fixture.ready=true
