schemas['ServiceStatus']['properties']['images'] = array(S)
schemas["Actions"] = obj({"repository": S, "organization": S, "runner_group_id": {"type": "integer", "minimum": 0, "maximum": 9007199254740991, "description": "Organization runner group ID; omit or use zero for the GitHub default group."}, "credential": S, "labels": array(S), "timeout_minutes": I}, ["credential", "labels"])
schemas["Actions"]["description"] = "Set exactly one of organization or repository. Existing repository configurations remain valid. Runner groups apply only to organization pools; repository access is managed by the group policy in GitHub."
schemas["Actions"]["properties"]["workspace_size_gib"] = {"type": "integer", "minimum": 2, "maximum": 16, "description": "Defaults to 2 GiB. Temporary disk reserved on the runner node per slot, shared by source, tools, Docker images and build files. Deleted after each job."}
schemas["Service"]["properties"]["actions"] = ref("Actions")
schemas["ActionsPool"] = obj({"application_id":S,"service":S,"project":S,"environment":S,"application_name":S,"revision":I,"config":ref("Service"),"removed":B,"message":S,"updated_at":T},["application_id","service","project","environment","application_name","revision","config","removed","message","updated_at"])
schemas["ActionsSlot"] = obj({"id":S,"application_id":S,"service":S,"runner_id":I,"phase":S,"created_at":T,"updated_at":T},["id","application_id","service","runner_id","phase","created_at","updated_at"])
route("/applications/{id}/actions","get","getManagedActions",obj({"items":array(obj({"pool":ref("ActionsPool"),"slots":array(ref("ActionsSlot"))},["pool","slots"]))},["items"]))
route("/actions/capabilities","get","getManagedActionsCapabilities",obj({"licensed":B,"runtime_ready":B,"message":S,"runner_image":S,"resource_profiles":schemas["Plan"]["properties"]["resource_profiles"]},["licensed","runtime_ready","message","runner_image"]),scope=True)
schemas['ActionsObservation'] = obj({'repository':S,'workflow':S,'run_id':I,'run_number':I,'attempt':I,'job_key':S,'branch':S,'sha':S},['repository','workflow','run_id','run_number','attempt','job_key','branch','sha'])
schemas['ActionsStep'] = obj({'name':S,'status':S,'conclusion':S,'number':I,'started_at':{'type':['string','null'],'format':'date-time'},'completed_at':{'type':['string','null'],'format':'date-time'}},['name','status','conclusion','number','started_at','completed_at'])
schemas['ActionsWorkflowJob'] = obj({'id':I,'run_id':I,'run_attempt':I,'name':S,'status':S,'conclusion':S,'runner_id':I,'runner_name':S,'started_at':{'type':['string','null'],'format':'date-time'},'completed_at':{'type':['string','null'],'format':'date-time'},'steps':array(ref('ActionsStep')),'steps_truncated':B},['id','run_id','run_attempt','name','status','conclusion','runner_id','runner_name','started_at','completed_at','steps'])
schemas['ActionsJob'] = obj({'slot_id':S,'runner_id':I,'observation':ref('ActionsObservation'),'job':{'anyOf':[ref('ActionsWorkflowJob'),{'type':'null'}]},'created_at':T,'updated_at':T},['slot_id','runner_id','observation','job','created_at','updated_at'])
route('/applications/{id}/actions/{service}/jobs','get','listActionsJobs',obj({'items':array(ref('ActionsJob')),'state':S,'message':S,'observed_at':T,'limit':I,'truncated':B},['items','state','message','observed_at','limit','truncated']))
route('/applications/{id}/actions/{service}/jobs/{slot}/logs','get','getActionsJobLogs',obj({'lines':array(obj({'number':I,'text':S},['number','text'])),'truncated':B,'source':S,'state':S,'message':S,'observed_at':T},['lines','truncated','source','state','message','observed_at']))
for endpoint in ['/applications/{id}/actions/{service}/jobs','/applications/{id}/actions/{service}/jobs/{slot}/logs']:
    for name in ['service'] + (['slot'] if '{slot}' in endpoint else []):
        paths[endpoint]['get']['parameters'].append({'name':name,'in':'path','required':True,'schema':S})
