"""Scoped external providers and native/external application secret references."""

schemas['SecretRef'] = {'type': 'object',
 'additionalProperties': False,
 'properties': {'ref': {'type': 'string',
                        'description': 'Existing application-scoped native secret name.'},
                'provider': {'type': 'string',
                             'description': 'Administrator-configured external provider name.'},
                'path': {'type': 'string',
                         'maxLength': 512,
                         'description': 'Relative path below the provider root; empty selects its '
                                        'root.'},
                'key': {'type': 'string',
                        'maxLength': 128,
                        'description': 'Vault string field or Infisical shared secret name.'}},
 'oneOf': [{'required': ['ref'],
            'not': {'anyOf': [{'required': ['provider']},
                              {'required': ['path']},
                              {'required': ['key']}]}},
           {'required': ['provider', 'key'], 'not': {'required': ['ref']}}]}

schemas['SecretProviderScope'] = {'type': 'object',
 'additionalProperties': False,
 'properties': {'project': {'type': 'string'},
                'environments': {'type': 'array',
                                 'maxItems': 32,
                                 'items': {'type': 'string'},
                                 'description': 'Empty means all environments of this project.'}},
 'required': ['project']}

schemas['SecretProvider'] = {'type': 'object',
 'additionalProperties': False,
 'properties': {'name': {'type': 'string'},
                'kind': {'type': 'string', 'enum': ['vault', 'infisical']},
                'endpoint': {'type': 'string',
                             'format': 'uri',
                             'description': 'Immutable HTTPS origin. Only installation '
                                            'administrators can configure providers.'},
                'mount': {'type': 'string', 'description': 'Vault/OpenBao KV v2 mount.'},
                'root_path': {'type': 'string', 'maxLength': 512},
                'project_id': {'type': 'string', 'description': 'Infisical project ID.'},
                'environment': {'type': 'string', 'description': 'Infisical environment slug.'},
                'namespace': {'type': 'string', 'description': 'Optional Vault namespace.'},
                'ca_cert': {'type': 'string',
                            'maxLength': 32768,
                            'description': 'Optional PEM certificate authority; TLS verification '
                                           'remains enabled.'},
                'private_cidrs': {'type': 'array',
                                  'maxItems': 16,
                                  'items': {'type': 'string'},
                                  'description': 'Explicit private network allowlist; loopback, '
                                                 'link-local and metadata endpoints are always '
                                                 'denied.'},
                'scopes': {'type': 'array',
                           'minItems': 1,
                           'maxItems': 32,
                           'items': {'$ref': '#/components/schemas/SecretProviderScope'}},
                'revision': {'type': 'integer', 'format': 'int64', 'readOnly': True},
                'created_at': {'type': 'string', 'format': 'date-time', 'readOnly': True},
                'updated_at': {'type': 'string', 'format': 'date-time', 'readOnly': True}},
 'required': ['name',
              'kind',
              'endpoint',
              'root_path',
              'scopes',
              'revision',
              'created_at',
              'updated_at']}

schemas['SecretProviderSummary'] = {'type': 'object',
 'additionalProperties': False,
 'properties': {'name': {'type': 'string'},
                'kind': {'type': 'string', 'enum': ['vault', 'infisical']}},
 'required': ['name', 'kind']}

schemas['SecretProviderInput'] = {'type': 'object',
 'additionalProperties': False,
 'properties': {'name': {'type': 'string'},
                'kind': {'type': 'string', 'enum': ['vault', 'infisical']},
                'endpoint': {'type': 'string',
                             'format': 'uri',
                             'description': 'Immutable HTTPS origin. Only installation '
                                            'administrators can configure providers.'},
                'mount': {'type': 'string', 'description': 'Vault/OpenBao KV v2 mount.'},
                'root_path': {'type': 'string', 'maxLength': 512},
                'project_id': {'type': 'string', 'description': 'Infisical project ID.'},
                'environment': {'type': 'string', 'description': 'Infisical environment slug.'},
                'namespace': {'type': 'string', 'description': 'Optional Vault namespace.'},
                'ca_cert': {'type': 'string',
                            'maxLength': 32768,
                            'description': 'Optional PEM certificate authority; TLS verification '
                                           'remains enabled.'},
                'private_cidrs': {'type': 'array',
                                  'maxItems': 16,
                                  'items': {'type': 'string'},
                                  'description': 'Explicit private network allowlist; loopback, '
                                                 'link-local and metadata endpoints are always '
                                                 'denied.'},
                'scopes': {'type': 'array',
                           'minItems': 1,
                           'maxItems': 32,
                           'items': {'$ref': '#/components/schemas/SecretProviderScope'}},
                'expected_revision': {'type': 'integer',
                                      'format': 'int64',
                                      'minimum': 0,
                                      'description': 'Zero creates; current revision updates '
                                                     'access or credentials. Source location and '
                                                     'network trust are immutable.'},
                'credentials': {'type': 'object',
                                'additionalProperties': False,
                                'properties': {'token': {'type': 'string',
                                                         'writeOnly': True,
                                                         'maxLength': 8192},
                                               'client_id': {'type': 'string',
                                                             'writeOnly': True,
                                                             'maxLength': 8192},
                                               'client_secret': {'type': 'string',
                                                                 'writeOnly': True,
                                                                 'maxLength': 8192}},
                                'writeOnly': True,
                                'description': 'Required on create; omit on update to retain '
                                               'credentials. Vault requires token, Infisical '
                                               'requires client_id and client_secret.'}},
 'required': ['kind', 'endpoint', 'scopes', 'expected_revision']}

paths['/secret-providers'] = {'get': {'operationId': 'listSecretProviders',
         'summary': 'List provider configuration for administrators, or names and kinds granted to '
                    'a deployment scope',
         'parameters': [{'name': 'project',
                         'in': 'query',
                         'required': False,
                         'schema': {'type': 'string'}},
                        {'name': 'environment',
                         'in': 'query',
                         'required': False,
                         'schema': {'type': 'string'}},
                        {'name': 'application',
                         'in': 'query',
                         'required': False,
                         'schema': {'type': 'string'}}],
         'responses': {'200': {'description': 'Successful response',
                               'content': {'application/json': {'schema': {'type': 'object',
                                                                           'additionalProperties': False,
                                                                           'properties': {'items': {'type': 'array',
                                                                                                    'items': {'oneOf': [{'$ref': '#/components/schemas/SecretProvider'},
                                                                                                                        {'$ref': '#/components/schemas/SecretProviderSummary'}]}}},
                                                                           'required': ['items']}}}}}}}

paths['/secret-providers/{name}'] = {'get': {'operationId': 'getSecretProvider',
         'summary': 'Read provider configuration without credentials (administrator only)',
         'parameters': [{'name': 'name',
                         'in': 'path',
                         'required': True,
                         'schema': {'type': 'string'}}],
         'responses': {'200': {'description': 'Successful response',
                               'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SecretProvider'}}}}}},
 'put': {'operationId': 'putSecretProvider',
         'summary': 'Create or update an external secret provider (administrator only)',
         'parameters': [{'name': 'name',
                         'in': 'path',
                         'required': True,
                         'schema': {'type': 'string'}}],
         'requestBody': {'required': True,
                         'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SecretProviderInput'}}}},
         'responses': {'200': {'description': 'Successful response',
                               'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SecretProvider'}}}},
                       '201': {'description': 'Successful response',
                               'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SecretProvider'}}}},
                       '409': {'description': 'Revision conflict'}}},
 'delete': {'operationId': 'deleteSecretProvider',
            'summary': 'Delete an unreferenced provider (administrator only)',
            'parameters': [{'name': 'name',
                            'in': 'path',
                            'required': True,
                            'schema': {'type': 'string'}}],
            'requestBody': {'required': True,
                            'content': {'application/json': {'schema': {'type': 'object',
                                                                        'additionalProperties': False,
                                                                        'properties': {'expected_revision': {'type': 'integer',
                                                                                                             'format': 'int64',
                                                                                                             'minimum': 1}},
                                                                        'required': ['expected_revision']}}}},
            'responses': {'200': {'description': 'Successful response',
                                  'content': {'application/json': {'schema': {'type': 'object',
                                                                              'additionalProperties': False,
                                                                              'properties': {'deleted': {'type': 'boolean'}},
                                                                              'required': ['deleted']}}}},
                          '409': {'description': 'Provider is referenced or its revision '
                                                 'changed'}}}}
