schemas['Network']['properties'].update({'virtual_network': S, 'segment': S})
schemas['NetworkSegment'] = obj({'applications': {'type': 'array', 'items': S, 'maxItems': 64}}, ['applications'])
schemas['VirtualNetworkSpec'] = obj({'schema_version': {'type': 'integer', 'enum': [1]}, 'name': S, 'description': S, 'segments': mapping(ref('NetworkSegment'))}, ['schema_version', 'name', 'description', 'segments'])
schemas['VirtualNetworkSummary'] = obj({'id': S, 'name': S, 'project': S, 'environment': S, 'description': S, 'segments': array(S), 'revision': I, 'updated_at': T}, ['id', 'name', 'project', 'environment', 'description', 'segments', 'revision', 'updated_at'])
schemas['VirtualNetworkConnection'] = obj({'application_id': S, 'application': S, 'service': S, 'network': S, 'segment': S, 'address': S, 'ports': array(ref('PrivatePort')), 'revision': I, 'status': S}, ['application_id', 'application', 'service', 'network', 'segment', 'address', 'ports', 'revision', 'status'])
schemas['VirtualNetworkDetail'] = obj({'network': ref('VirtualNetworkSummary'), 'spec': ref('VirtualNetworkSpec'), 'toml': S, 'connections': array(ref('VirtualNetworkConnection')), 'truncated': B, 'can_manage': B}, ['network', 'spec', 'toml', 'connections', 'truncated', 'can_manage'])
schemas['VirtualNetworkInput'] = obj({'project': S, 'environment': S, 'spec': ref('VirtualNetworkSpec'), 'toml': S, 'expected_id': S, 'expected_revision': I}, ['project', 'environment'])
schemas['VirtualNetworkCreate'] = obj(schemas['VirtualNetworkInput']['properties'], ['project', 'environment', 'expected_revision'])
schemas['VirtualNetworkUpdate'] = obj(schemas['VirtualNetworkInput']['properties'], ['project', 'environment', 'expected_id', 'expected_revision'])
schemas['VirtualNetworkPlan'] = obj({'spec': ref('VirtualNetworkSpec'), 'previous': {'anyOf': [ref('VirtualNetworkSpec'), {'type': 'null'}]}, 'toml': S, 'expected_id': S, 'expected_revision': I}, ['spec', 'previous', 'toml', 'expected_id', 'expected_revision'])
route('/virtual-networks', 'get', 'listVirtualNetworks', obj({'items': array(ref('VirtualNetworkSummary')), 'can_manage': B}, ['items', 'can_manage']), scope=True)
route('/virtual-networks/{name}', 'get', 'getVirtualNetwork', ref('VirtualNetworkDetail'), scope=True)
route('/virtual-networks/{name}/candidates', 'get', 'listVirtualNetworkCandidates', obj({'items': array(obj({'id': S, 'name': S, 'revision': I, 'services': array(S)}, ['id', 'name', 'revision', 'services']))}, ['items']), scope=True)
paths['/virtual-networks/{name}/candidates']['get']['parameters'].append({'name': 'name', 'in': 'path', 'required': True, 'schema': S})
route('/virtual-networks/plan', 'post', 'planVirtualNetwork', ref('VirtualNetworkPlan'), ref('VirtualNetworkInput'))
route('/virtual-networks', 'post', 'createVirtualNetwork', ref('VirtualNetworkSummary'), ref('VirtualNetworkCreate'), '201')
route('/virtual-networks/{name}', 'put', 'updateVirtualNetwork', ref('VirtualNetworkSummary'), ref('VirtualNetworkUpdate'))
route('/virtual-networks/{name}', 'delete', 'deleteVirtualNetwork', obj({'deleted': B}, ['deleted']), obj({'project': S, 'environment': S, 'expected_id': S, 'expected_revision': I, 'confirmation': S}, ['project', 'environment', 'expected_id', 'expected_revision', 'confirmation']))
for operation in paths['/virtual-networks/{name}'].values():
    operation['parameters'].append({'name': 'name', 'in': 'path', 'required': True, 'schema': S})
