import { createFileRoute, Link, Outlet, useLocation } from '@tanstack/react-router'
import { Empty, ErrorState, Loading, Note, PageHeader, Status } from '../components/shared'
import { Button } from '../components/ui/button'
import { Icon } from '../components/icons'
import { managedPlatformName, platformSearch, useManagedPlatforms } from '../lib/managed-platforms'

export const Route = createFileRoute('/platforms')({ validateSearch: platformSearch, component: Page })
function Page(){return useLocation().pathname==='/platforms'?<Platforms/>:<Outlet/>}
function Platforms(){const scope=Route.useSearch();const query=useManagedPlatforms(scope.project,scope.environment);return <div className="ops-page"><PageHeader title="Platforms" description="Owned application platforms with durable revisions and operations." action={<Button onClick={()=>void query.refetch()} disabled={query.isFetching}><Icon name="refresh" size={14}/>Refresh</Button>}/>{query.error&&query.data&&<Note>Refresh failed. Showing the last received platform list.</Note>}{query.isPending?<Loading/>:query.error&&!query.data?<ErrorState error={query.error}/>:!query.data.items.length?<Empty title="No managed platforms" description="Neon and Supabase remain unavailable until native qualification is complete."/>:<div className="db-catalog">{query.data.items.map((item)=><article className="db-catalog-card" key={item.id}><div className="db-catalog-card-heading"><Icon name="server" size={28}/><div className="min-w-0"><h2><Link to="/platforms/$platformId" params={{platformId:item.id}} search={{project:item.project,environment:item.environment}}>{item.spec.name}</Link></h2><p className="[overflow-wrap:anywhere]">{managedPlatformName(item.spec.kind)} {item.spec.version}</p></div><Status value={item.status}/></div><div className="db-catalog-footer"><span>{typeof item.observation.ready_components==='number'&&typeof item.observation.expected_components==='number'?`${item.observation.ready_components} / ${item.observation.expected_components} ready`:'Not observed'}</span><span>{item.project} / {item.environment}</span><span className="ml-auto">r{item.revision}</span></div></article>)}</div>}</div>}
