import { createFileRoute, Link, Outlet, useLocation } from '@tanstack/react-router'
import { Empty, ErrorState, Loading, Note, PageHeader, Status } from '../components/shared'
import { Button } from '../components/ui/button'
import { Icon } from '../components/icons'
import { useResourceScope, useScope, canAccess } from '../lib/scope'
import { managedPlatformName, useManagedPlatform, useManagedPlatformOperations } from '../lib/managed-platforms'

export const Route=createFileRoute('/platforms/$platformId')({component:Page})
function Page(){const id=Route.useParams().platformId;return useLocation().pathname===`/platforms/${id}`?<Detail/>:<Outlet/>}
function Detail(){const id=Route.useParams().platformId;const query=useManagedPlatform(id);const operations=useManagedPlatformOperations(id);const {identity}=useScope();useResourceScope(query.data);if(query.isPending)return <Loading/>;if(query.error&&!query.data)return <ErrorState error={query.error}/>;const item=query.data!;const canManage=!identity.application&&canAccess(identity,item.project,'deployments:write');return <div className="ops-page"><PageHeader title={item.spec.name} description={`${managedPlatformName(item.spec.kind)} ${item.spec.version}`} action={<div className="flex flex-wrap gap-2"><Button onClick={()=>{void query.refetch();void operations.refetch()}}><Icon name="refresh" size={14}/>Refresh</Button>{canManage&&<Button asChild variant="destructive"><Link to="/platforms/$platformId/delete" params={{platformId:id}} search={{project:item.project,environment:item.environment}}><Icon name="trash" size={14}/>Delete</Link></Button>}</div>}/>{query.error&&<Note>Refresh failed. Showing the last received platform state.</Note>}<div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2"><section className="db-panel"><div className="db-panel-heading"><h2>Runtime</h2><Status value={item.status}/></div><dl className="db-catalog-facts px-4"><div><dt>Revision</dt><dd>{item.revision}</dd></div><div><dt>Namespace</dt><dd>{item.observation.namespace_uid?'Owned':'Not observed'}</dd></div><div><dt>Components</dt><dd>{typeof item.observation.ready_components==='number'&&typeof item.observation.expected_components==='number'?`${item.observation.ready_components} / ${item.observation.expected_components}`:'Not observed'}</dd></div></dl></section><section className="db-panel"><div className="db-panel-heading"><h2>Activity</h2></div>{operations.error&&operations.data&&<Note>Activity refresh failed. Showing the last received operations.</Note>}{operations.isPending?<Loading/>:operations.error&&!operations.data?<ErrorState error={operations.error}/>:!operations.data.items.length?<Empty title="No operations" description="No lifecycle operation has been accepted."/>:<ul className="grid min-w-0 grid-cols-1 gap-3 p-4">{operations.data.items.map(op=><li key={op.id} className="min-w-0 grid grid-cols-1 gap-1"><div className="flex min-w-0 flex-wrap items-center gap-2"><Status value={op.status}/><span>{op.kind}</span><span className="ml-auto">r{op.revision}</span></div><div className="text-sm text-muted-foreground [overflow-wrap:anywhere]">{op.phase} · Attempt {op.attempt}</div>{op.message&&<p className="text-sm [overflow-wrap:anywhere]">{op.message}</p>}<time className="text-xs text-muted-foreground" dateTime={op.created_at}>{new Date(op.created_at).toLocaleString()}</time></li>)}</ul>}</section></div></div>}
