ALTER TABLE identities ADD COLUMN email text;
CREATE UNIQUE INDEX identities_email ON identities(lower(email)) WHERE email IS NOT NULL;
ALTER TABLE identities ADD COLUMN email_verified boolean NOT NULL DEFAULT false;
ALTER TABLE identities ADD COLUMN owner boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX single_installer_owner ON identities(owner) WHERE owner;
ALTER TABLE identities ADD COLUMN password_hash bytea;
ALTER TABLE identities ADD COLUMN failed_logins integer NOT NULL DEFAULT 0;
ALTER TABLE identities ADD COLUMN locked_until timestamptz;
ALTER TABLE identities ADD COLUMN totp_secret bytea;
ALTER TABLE identities ADD COLUMN totp_step bigint NOT NULL DEFAULT -1;
ALTER TABLE identities ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE api_keys ADD COLUMN kind text NOT NULL DEFAULT 'machine' CHECK(kind IN ('machine','browser','cli','integration'));
CREATE INDEX human_sessions ON api_keys(identity_id,created_at DESC) WHERE kind<>'machine';
CREATE TABLE teams(id text PRIMARY KEY,name text NOT NULL CHECK(length(name) BETWEEN 1 AND 100),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE team_members(team_id text NOT NULL REFERENCES teams(id) ON DELETE CASCADE,identity_id text NOT NULL REFERENCES identities(id),role text NOT NULL CHECK(role IN ('owner','admin','member')),PRIMARY KEY(team_id,identity_id));
CREATE TABLE project_members(project text NOT NULL REFERENCES projects(name) ON DELETE CASCADE,identity_id text NOT NULL REFERENCES identities(id),role text NOT NULL CHECK(role IN ('admin','developer','viewer')),PRIMARY KEY(project,identity_id));
CREATE TABLE project_teams(project text NOT NULL REFERENCES projects(name) ON DELETE CASCADE,team_id text NOT NULL REFERENCES teams(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('admin','developer','viewer')),PRIMARY KEY(project,team_id));
CREATE TABLE invites(id text PRIMARY KEY,digest bytea NOT NULL,email text NOT NULL,team_id text REFERENCES teams(id) ON DELETE CASCADE,project text REFERENCES projects(name) ON DELETE CASCADE,role text NOT NULL,created_by text NOT NULL REFERENCES identities(id),expires_at timestamptz NOT NULL,accepted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CHECK(team_id IS NOT NULL OR project IS NOT NULL));
CREATE INDEX invite_expiry ON invites(expires_at);
CREATE TABLE auth_challenges(id text PRIMARY KEY,kind text NOT NULL,digest bytea NOT NULL,data jsonb NOT NULL DEFAULT '{}',expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX auth_challenge_expiry ON auth_challenges(expires_at);
CREATE TABLE recovery_codes(identity_id text NOT NULL REFERENCES identities(id) ON DELETE CASCADE,digest bytea NOT NULL,PRIMARY KEY(identity_id,digest));
CREATE TABLE oauth_identities(provider text NOT NULL,subject text NOT NULL,identity_id text NOT NULL REFERENCES identities(id),PRIMARY KEY(provider,subject),UNIQUE(provider,identity_id));
CREATE TABLE passkeys(id text PRIMARY KEY,identity_id text NOT NULL REFERENCES identities(id),name text NOT NULL,credential jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),last_used_at timestamptz);
CREATE INDEX passkeys_owner ON passkeys(identity_id);
CREATE TABLE device_codes(id text PRIMARY KEY,digest bytea NOT NULL,user_code text NOT NULL UNIQUE,project text NOT NULL,environment text NOT NULL,permissions text[] NOT NULL,identity_id text REFERENCES identities(id),approved boolean,expires_at timestamptz NOT NULL,consumed_at timestamptz,last_polled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX device_expiry ON device_codes(expires_at);
