/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications.$applicationId'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/infrastructure': typeof InfrastructureRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infrastructure': typeof InfrastructureRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/infrastructure': typeof InfrastructureRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/infrastructure'
    | '/session'
    | '/settings'
    | '/api/$'
    | '/applications/$applicationId'
    | '/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/infrastructure'
    | '/session'
    | '/settings'
    | '/api/$'
    | '/applications/$applicationId'
    | '/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/infrastructure'
    | '/session'
    | '/settings'
    | '/api/$'
    | '/applications/$applicationId'
    | '/deployments/$deploymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfrastructureRoute: typeof InfrastructureRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfrastructureRoute: InfrastructureRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
